technique-lang/technique

lib/Technique/Evaluator.hs, lib/Technique/Formatter.hs, lib/Technique/Language.hs, package.yaml, tests/CheckAbstractSyntax.hs, tests/ExampleProcedure.hs
Reorganize test suite so that _tests/CheckAbstractSyntax.hs_ only has actual unit tests and _tests/ExampleProcedure.hs_ has the sample instance of the AST for experimenting with.
=> Extract example procedure to separate file

lib/Technique/Formatter.hs, lib/Technique/Parser.hs, lib/Technique/Quantity.hs, tests/CheckSkeletonParser.hs, tests/ExampleProcedure.hs
Implement parsing of Blocks, currently as a list of Statements. Much complexity arises from our desire to quietly support semicolon as an optional statement separator. At present those wouldn't be preserved on output but we can correct that with a better intermediate type between Block and Statement.
=> Parse Blocks of Statements

lib/Technique/Formatter.hs, lib/Technique/Language.hs, lib/Technique/Parser.hs, tests/CheckAbstractSyntax.hs, tests/CheckSkeletonParser.hs, tests/ExampleProcedure.hs
Ordinarily statements in a blocks are separated by newlines, but optionally they can be separated by a `;` character. Support this in parser and output formatter.
This patch also deals with the problem of parsing a block which happens to not have newlines after opening brace or before closing brace. While we don't want this as normal practice it is entirely reasonable to parse it as a valid block.
=> Add support for series of statements

lib/Technique/Formatter.hs, lib/Technique/Language.hs, lib/Technique/Parser.hs, tests/CheckSkeletonParser.hs, tests/ExampleProcedure.hs
Enhance parser to support parsing of operators. The language only has a few fixed operators: `|` and `&` for waiting, and `+` for combining tablets.
=> Support parsing operators

lib/Technique/Formatter.hs, package.yaml, src/TechniqueMain.hs, src/TechniqueUser.hs, stack.yaml, symlinks
Implement `check` and `format` commands to the _technique_ program, driving the Technique.Parser and Technique.Formatter modules respectively.
=> Implement front-end for parser and round-trip output formatter

lib/Technique/Formatter.hs, lib/Technique/Parser.hs, lib/Technique/Quantity.hs, package.yaml, src/TechniqueMain.hs, src/TechniqueUser.hs, tests/CheckAbstractSyntax.hs, tests/CheckSkeletonParser.hs, tests/ExampleProcedure.hs
We can now handle
180 °C
as a Quantity!
Fixes several whitespace bugs that crept in, including one where function application was no longer working.
Completes the round trip of the format command: if redirected to a file plain text is emitted, but if the output is to terminal then syntax highlighting will be rendered. Beautiful.
=> Parse of quanties with units

lib/Technique/Parser.hs, package.yaml, tests/CheckSkeletonParser.hs, tests/ParseSnippet.hs
After much frustration we independently discovered that the `try a <|> b` pattern leads to well intentioned error message being swallowed by backtracking with the result that misparse of a number, say, ends up as an error about a misplaced `{` 15 lines earlier. Egad!
Thanks to @ezyang's blog post titled [Parsec: “try a <|> b” considered harmful](http://blog.ezyang.com/2014/05/parsec-try-a-or-b-considered-harmful/) on this pattern for having clarified that we had indeed hit a fundamental design {limitation, feature, flaw} of parser combinators.
This rips out all the use of `try <|>` and replaces it with scans using **megaparsec**'s `lookAhead` to determine wither to commit to a given alternative branch.
=> Replace use of try with lookAhead

lib/Technique/Diagnostics.hs, lib/Technique/Failure.hs, lib/Technique/Formatter.hs, lib/Technique/Internal.hs, lib/Technique/Language.hs, lib/Technique/Parser.hs, lib/Technique/Quantity.hs, lib/Technique/Translate.hs, package.yaml, src/TechniqueMain.hs, src/TechniqueUser.hs, stack.yaml, tests/CheckAbstractSyntax.hs, tests/CheckConcreteSyntax.hs, tests/CheckSkeletonParser.hs, tests/CheckTranslationStage.hs, tests/ExampleProcedure.hs, tests/TestSuite.hs
Reverse the attempt to have **megaparsec** render all the compilation errors, and instead gather details of a failure encountered during parsing phase as just one of the ways that compilation can fail. Rebuild a renderer of parse error messages and use the same machinery to render the various translation phase problems.
=> Render compilation errors arising from translation phase

lib/Technique/Builtins.hs, lib/Technique/Failure.hs, lib/Technique/Internal.hs, lib/Technique/Language.hs, lib/Technique/Parser.hs, lib/Technique/Translate.hs, package.yaml, src/TechniqueUser.hs, tests/CheckSkeletonParser.hs, tests/CheckTranslationStage.hs, tests/ExampleProcedure.hs
Colour the unexpected (if any), expected tokens [for parsing phase] and emphasize identifiers as variables, applied functions, or procedure declcarations in the compiler error messages.
=> Colour tokens in compiler error messages

lib/Technique/Evaluator.hs, lib/Technique/Translate.hs
I was browsing through the code to get familiar with things and my editor found a few things that it wasn't happy with.
There are a few other things (unused vars, non-canonical monoid definitions, and partial pattern match functions) that flag up, but I don't (yet) have enough context to tackle those.
I look forward to your feedback. :)
All best!
=> Fix a spelling error and some lint nits.

src/language/types.rs, src/main.rs, src/parsing/mod.rs, src/parsing/parser.rs
Initial work to construct a front-end parser. This version forks from the direct use of the regex crate as started in #44 and the attempt to use context scopes in the way the highlighter package does that we started in #45, but instead creates a parser that is hybrid between stateful and pure.
The approach taken is a series of `is_*()` functions to identify whether the next input is what is expected (or to evaluate possibilities), and then a variety of `take_*()` methods on the Parser type to scan from a start predicate to an end one. This allows us to identify blocks of input and then pass the nested content to another parser without that inner layer having to worry about it's end condition.
Extensive testing has been added for innumerable corner cases.
=> Use taking blocks to parse Technique procedure files

src/language/types.rs, src/parsing/parser.rs
Improve performance by caching the regex::Regex objects that are allocated at runtime when  regular expression is compiled. Do this using the usual trick of caching them behind OnceLock references, but rather than a global variable per regex, use a custom `regex!` macro to put the
allocation and unwrapping in place at each call site for us instead.
=> Improve performance by caching Regex objects

src/error/display.rs, src/main.rs, src/parsing/mod.rs, src/parsing/parser.rs, tests/parsing/parser.rs
When reporting errors, we now report both a succinct error message and a more detailed explanation of what it means and what good input code would look like. To that end, we enrich the details for each of the current failure modes in ParsingError and change TechniqueError to take both.
Update the display of errors to include line and column number, and a pointer to where in the failed line the problem occurred. We also emit the filename, as is conventional in compiler error messsages, which required plumbing the Path through the call stack.
Finally we have updated the check command to have an `--output` option which takes `native` to dump the AST, otherwise either exiting 1 and reporting the error, or exiting 0 indicating a pass.
=> Improve display of error messages

src/parsing/mod.rs, src/parsing/parser.rs, tests/parsing/errors.rs, tests/parsing/mod.rs
Having gone to the trouble in #57 to present richer error messages, we've needed to go through some refinement to actually emit these appropriate errors in various scenarios. This branch also adds some preliminary efforts to detect malformed or invalid input in such a way that we can guess the user's intent and give a better error as a result.
=> Improve parsing errors

src/error/display.rs, src/main.rs, src/parsing/mod.rs, src/parsing/parser.rs
Further improvements to the detection and output of errors.
The "ok" string is now only printed from the _technique check_ command; if running _format_ then it just validates silently before outputting the formatted code.
Filename, line, and columns are now printed consistently in error messages be they concise or full.
A significant improvement is the handling of mistakes made by the user when writing signatures and when those signatures are spread over multiple lines. Both were failing, the first with InvalidProcedure rather than the more specific InvalidSignature you'd expect and the error offset was not pointing to the mistake in the signature.
=> Improve detection of problems with signatures

Cargo.toml, LICENSE, src/error/display.rs, src/formatting/formatter.rs, src/language/mod.rs, src/language/quantity.rs, src/language/types.rs, src/parsing/parser.rs
The last thing remaining needing support from the v0 version of the language was the Quantity type, whereby numeric values can have uncertainty, magnitude, and units, for example
5.9722 ± 0.0006 × 10²⁴ kg
We add support in the parser for detecting quantity numericals, and appropriate code for presenting them nicely when formatting output.
It also turned out that we weren't accounting for the width of Unicode characters when printing error messages. That is fixed, along with ensuring that the caret points to the best location relative to where the problem is.
=> Parse and format Quantities

src/main.rs
Add an `--output` option the _render_ command (analogous to the option of the same name in the _check_ command) to output the intermediate Typst markup that will be passed to the typesetter.
=> Output raw typst markup if debugging rendering

src/formatting/formatter.rs, src/formatting/renderer.rs, tests/formatting/formatter.rs
Use references to avoid unnecessary allocation and copying in the code formatter. That also allows a nifty optimization to have a lookup table of multiples of 4 space indents, meaning no allocation is needed for that very common case either.
=> Use references in formatter

src/parsing/parser.rs
Much to my surprise, a code inline in a descriptive wasn't working if it was spread over several lines. This branch fixes that scenario so an inline containing a multiline string or even just a function call spread over several lines is still valid.
=> Support mutli-line code inlines in descriptives

Cargo.lock, Cargo.toml, examples/golden/ManyAttributes.t, src/formatting/formatter.rs, src/parsing/parser.rs
We had the notion of both roles and places in Attributes in Technique v0, but so far in v1 we'd only implemented role Attributes with the `@role` notation. This branch adds `^place`, using the caret we're now using as the marker for place Attributes.
=> Support places in Attribute scopes

examples/golden/Bedtime.t, src/formatting/formatter.rs, src/parsing/parser.rs
Encountered a nasty bug that a document with only top-level Sections, which by design is a valid and admissible Technique (and is even how `struct Technique` is defined) was not being parsed but worse was being silently discarded.
Fixed an omission in the formatter where sections were not being preceded by a blank line.
Added an example to the golden tests to enforce this remaining correct in the future.
=> Fix parsing of documents with only top-level Sections

Cargo.lock, Cargo.toml, src/main.rs, src/parsing/mod.rs, src/parsing/parser.rs, src/problem/format.rs, src/problem/messages.rs, tests/broken/BadDeclaration.tq, tests/parsing/errors.rs, tests/parsing/parser.rs
Until now we have just exited on detecting the first parsing or validation error, but the forthcoming language server will need to know where all the problems are. So the next step in maturing the parser is collecting more than a single error at a time when checking the validity of a document.
The Parser state object is updated to include a Vec<ParsingError> that the parser (and subparsers) can contribute to.
Finally, when reporting errors we deduplicate, with more specific messages overriding enclosing general ones. This is an admittedly rare occurrence, as usually fail-fast short-circuiting will cause a single error to propagate, but in the event nesting results in multiple errors at the same site we trim it down to a single message.
=> Collect and display all detected errors in an input document

.github/workflows/release.yaml
Update the `Release` Workflow to use the GitHub Actions "matrix" feature to build on Mac OS and Windows in addition to Linux.
=> Prepare releases for other operating systems

Cargo.lock, Cargo.toml, examples/minimal/SimpleList.tq, src/parsing/parser.rs, tests/parsing/samples.rs
Documents can be either series of Procedures (containing Technique) or a simple Techniques (with only top-level steps). For some reason parsing of the latter had regressed. Fixed.
Add an example file to ensure simple documents like this are readily verifiable and ensure technique documents in both _tests/samples/_ and _examples/minimal/_ files are checked by the test suite.
=> Fix parsing of simple Techniques with only top-level steps
